package com.growmighty.lectures.firstday.settlement.application;

public enum ProjectOutcomeProcessingStatus {

    SETTLEMENT_CONFIRMED,
    SETTLEMENT_ALREADY_CONFIRMED,
    PAYMENT_CANCELLATION_COMPLETED,
    PAYMENT_CANCELLATION_PROCESSING,
    PAYMENT_CANCELLATION_RETRYABLE_FAILED,
    PAYMENT_CANCELLATION_FINAL_FAILED,
    PAYMENT_CANCELLATION_UNKNOWN,
    OUTCOME_CONFLICT
}
